project:
  type: book

book:
  title: "Reinforcement Learning Quarto"
  author: "Norah Jones"
  date: "19/9/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - Tarea 1.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

